export const JOB_FAMILY_TAXONOMY_VERSION = "job_family_taxonomy_v1";

export const JOB_FAMILY_KEYS = [
  "construction_trades",
  "craft_maintenance_repair",
  "industry_production",
  "logistics_supply_warehouse",
  "transport_delivery_driving",
  "security_safety",
  "cleaning_hygiene",
  "hospitality_food_tourism",
  "healthcare_social_care",
  "retail_sales_checkout",
  "agriculture_agro",
  "admin_support",
  "finance_accounting_audit",
  "hr_recruitment_training",
  "marketing_communication_content",
  "commercial_business_customer",
  "tech_data_product_design",
  "legal_compliance",
  "education_research",
  "public_ngo_development",
  "management_project",
  "other_uncategorized",
] as const;

export type JobFamilyKey = (typeof JOB_FAMILY_KEYS)[number];

export type JobFamilyDefinition = {
  key: JobFamilyKey;
  label: string;
  short_label: string;
  aliases_fr: string[];
  aliases_en: string[];
  strong_title_aliases: string[];
  context_aliases: string[];
  skill_aliases: string[];
  company_hints: string[];
  source_hints: string[];
  legacy_hints: string[];
  adjacent_families: JobFamilyKey[];
  status: "active";
};

function defineFamily(definition: JobFamilyDefinition): JobFamilyDefinition {
  return definition;
}

export const JOB_FAMILY_ORDER: JobFamilyKey[] = [...JOB_FAMILY_KEYS];

export const JOB_FAMILY_TAXONOMY: Record<JobFamilyKey, JobFamilyDefinition> = {
  construction_trades: defineFamily({
    key: "construction_trades",
    label: "BTP / construction / travaux",
    short_label: "BTP / construction",
    aliases_fr: [
      "btp",
      "construction",
      "travaux",
      "gros oeuvre",
      "second oeuvre",
      "chantier",
      "batiment",
      "travaux publics",
      "genie civil",
    ],
    aliases_en: [
      "construction",
      "civil works",
      "public works",
      "building works",
      "site works",
    ],
    strong_title_aliases: [
      "conducteur de travaux",
      "chef de chantier",
      "macon",
      "coffreur",
      "ferrailleur",
      "grutier",
      "civil engineer",
      "site engineer",
      "quantity surveyor",
    ],
    context_aliases: [
      "chantier",
      "beton",
      "ouvrage",
      "gros oeuvre",
      "fondations",
      "charpente",
    ],
    skill_aliases: [
      "autocad",
      "revit",
      "topographie",
      "lecture de plans",
      "terrassement",
    ],
    company_hints: ["construction", "bat", "travaux", "btp"],
    source_hints: ["construction", "btp"],
    legacy_hints: [],
    adjacent_families: [
      "craft_maintenance_repair",
      "industry_production",
      "management_project",
    ],
    status: "active",
  }),
  craft_maintenance_repair: defineFamily({
    key: "craft_maintenance_repair",
    label: "Artisanat / maintenance / réparation",
    short_label: "Artisanat / maintenance",
    aliases_fr: [
      "artisanat",
      "maintenance",
      "reparation",
      "depannage",
      "atelier",
      "service technique",
    ],
    aliases_en: [
      "maintenance",
      "repair",
      "technician",
      "workshop",
      "field service",
    ],
    strong_title_aliases: [
      "technicien de maintenance",
      "superviseur maintenance",
      "maintenance supervisor",
      "electromecanicien",
      "mecanicien",
      "mechanical technician",
      "electrical technician",
      "electricien",
      "plombier",
      "frigoriste",
      "maintenance technician",
      "service technician",
    ],
    context_aliases: [
      "panne",
      "maintenance preventive",
      "maintenance curative",
      "depannage",
      "atelier",
      "troubleshooting",
      "rotating equipment",
      "field technician",
      "intervention",
      "auxiliary systems",
    ],
    skill_aliases: [
      "mecanique",
      "electrique",
      "hydraulique",
      "pneumatique",
      "diagnostic technique",
      "cmms",
      "turbine",
      "compressor",
      "generator",
      "turbo generator",
      "turbo compressor",
    ],
    company_hints: ["maintenance", "repair", "service technique"],
    source_hints: ["maintenance", "repair"],
    legacy_hints: [],
    adjacent_families: [
      "construction_trades",
      "industry_production",
      "transport_delivery_driving",
    ],
    status: "active",
  }),
  industry_production: defineFamily({
    key: "industry_production",
    label: "Industrie / production / usine",
    short_label: "Industrie / production",
    aliases_fr: [
      "industrie",
      "production",
      "usine",
      "fabrication",
      "manufacturing",
      "ligne de production",
    ],
    aliases_en: ["industry", "production", "factory", "manufacturing", "plant"],
    strong_title_aliases: [
      "operateur de production",
      "chef d equipe production",
      "technicien production",
      "production supervisor",
      "plant manager",
      "manufacturing engineer",
    ],
    context_aliases: [
      "atelier de production",
      "rendement",
      "ligne",
      "cadence",
      "qualite production",
    ],
    skill_aliases: [
      "lean",
      "5s",
      "haccp",
      "qualite",
      "maintenance industrielle",
    ],
    company_hints: ["industrie", "factory", "manufacturing", "plant"],
    source_hints: ["industrie", "manufacturing"],
    legacy_hints: [],
    adjacent_families: [
      "construction_trades",
      "craft_maintenance_repair",
      "logistics_supply_warehouse",
    ],
    status: "active",
  }),
  logistics_supply_warehouse: defineFamily({
    key: "logistics_supply_warehouse",
    label: "Logistique / supply / magasin / entrepôt",
    short_label: "Logistique / supply",
    aliases_fr: [
      "logistique",
      "supply",
      "approvisionnement",
      "magasin",
      "entrepot",
      "stock",
    ],
    aliases_en: [
      "logistics",
      "supply chain",
      "warehouse",
      "inventory",
      "procurement",
    ],
    strong_title_aliases: [
      "magasinier",
      "gestionnaire de stock",
      "responsable logistique",
      "chef d equipe logistique",
      "rigger",
      "lifting supervisor",
      "crane operator",
      "forklift operator",
      "supply chain manager",
      "warehouse supervisor",
      "procurement officer",
      "storekeeper",
    ],
    context_aliases: [
      "stock",
      "inventaire",
      "entrepot",
      "achat",
      "approvisionnement",
      "magasin",
      "lifting operations",
      "rigging",
      "offloading",
      "crane",
      "winch",
      "forklift",
      "material transfer",
      "support vessel",
    ],
    skill_aliases: [
      "sap mm",
      "wms",
      "gestion de stock",
      "incoterms",
      "procurement",
      "rigging",
      "lifting plan",
      "crane operations",
      "forklift",
      "offloading",
    ],
    company_hints: ["logistique", "supply", "warehouse"],
    source_hints: ["logistique", "supply"],
    legacy_hints: ["operations_supply"],
    adjacent_families: [
      "industry_production",
      "transport_delivery_driving",
      "retail_sales_checkout",
      "management_project",
    ],
    status: "active",
  }),
  transport_delivery_driving: defineFamily({
    key: "transport_delivery_driving",
    label: "Transport / conduite / livraison",
    short_label: "Transport / conduite",
    aliases_fr: [
      "transport",
      "conduite",
      "livraison",
      "chauffeur",
      "conducteur",
    ],
    aliases_en: ["transport", "driving", "delivery", "fleet"],
    strong_title_aliases: [
      "chauffeur livreur",
      "chauffeur poids lourd",
      "conducteur routier",
      "delivery driver",
      "fleet coordinator",
    ],
    context_aliases: ["tournee", "livraison", "permis", "camion", "flotte"],
    skill_aliases: ["permis c", "permis ec", "gps", "gestion de flotte"],
    company_hints: ["transport", "delivery", "fleet"],
    source_hints: ["transport", "delivery"],
    legacy_hints: [],
    adjacent_families: [
      "logistics_supply_warehouse",
      "craft_maintenance_repair",
    ],
    status: "active",
  }),
  security_safety: defineFamily({
    key: "security_safety",
    label: "Sécurité / gardiennage / sûreté",
    short_label: "Sécurité / sûreté",
    aliases_fr: [
      "securite",
      "gardiennage",
      "surete",
      "surveillance",
      "protection",
    ],
    aliases_en: [
      "safety",
      "guarding",
      "surveillance",
      "protection",
    ],
    strong_title_aliases: [
      "agent de securite",
      "vigile",
      "superviseur securite",
      "security officer",
      "security guard",
      "hse officer",
    ],
    context_aliases: [
      "controle d acces",
      "rondes",
      "videosurveillance",
      "incidents",
      "sse",
    ],
    skill_aliases: [
      "hse",
      "safety",
      "secourisme",
      "gestion des risques",
      "cctv",
    ],
    company_hints: ["security", "surete", "hse"],
    source_hints: ["security", "hse"],
    legacy_hints: [],
    adjacent_families: ["cleaning_hygiene", "management_project"],
    status: "active",
  }),
  cleaning_hygiene: defineFamily({
    key: "cleaning_hygiene",
    label: "Nettoyage / entretien / hygiène",
    short_label: "Nettoyage / entretien",
    aliases_fr: [
      "nettoyage",
      "entretien",
      "hygiene",
      "proprete",
      "assainissement",
    ],
    aliases_en: [
      "cleaning",
      "janitorial",
      "housekeeping",
      "sanitation",
      "hygiene",
    ],
    strong_title_aliases: [
      "agent d entretien",
      "technicien de surface",
      "femme de chambre",
      "housekeeper",
      "cleaner",
      "janitor",
    ],
    context_aliases: [
      "entretien des locaux",
      "proprete",
      "desinfection",
      "hygiene",
    ],
    skill_aliases: ["bio nettoyage", "desinfection", "housekeeping"],
    company_hints: ["clean", "hygiene", "entretien"],
    source_hints: ["cleaning", "housekeeping"],
    legacy_hints: [],
    adjacent_families: [
      "hospitality_food_tourism",
      "security_safety",
      "healthcare_social_care",
    ],
    status: "active",
  }),
  hospitality_food_tourism: defineFamily({
    key: "hospitality_food_tourism",
    label: "Restauration / cuisine / hôtellerie / tourisme",
    short_label: "Restauration / hôtellerie",
    aliases_fr: [
      "restauration",
      "cuisine",
      "hotellerie",
      "tourisme",
      "hebergement",
    ],
    aliases_en: ["hospitality", "food service", "kitchen", "hotel", "tourism"],
    strong_title_aliases: [
      "cuisinier",
      "chef de cuisine",
      "chef de partie",
      "chef de rang",
      "serveur",
      "receptionniste hotel",
      "hotel receptionist",
      "cook",
      "waiter",
    ],
    context_aliases: [
      "restaurant",
      "cuisine",
      "service en salle",
      "hotel",
      "tourisme",
    ],
    skill_aliases: ["haccp", "service client", "restauration", "reception"],
    company_hints: ["hotel", "restaurant", "tourism"],
    source_hints: ["hotel", "restaurant"],
    legacy_hints: [],
    adjacent_families: [
      "cleaning_hygiene",
      "retail_sales_checkout",
      "commercial_business_customer",
    ],
    status: "active",
  }),
  healthcare_social_care: defineFamily({
    key: "healthcare_social_care",
    label: "Santé / soins / aide à la personne / social",
    short_label: "Santé / social",
    aliases_fr: [
      "sante",
      "soins",
      "aide a la personne",
      "social",
      "medical",
      "paramedical",
    ],
    aliases_en: ["healthcare", "care", "medical", "clinical", "social care"],
    strong_title_aliases: [
      "infirmier",
      "aide soignant",
      "sage femme",
      "medecin",
      "assistant social",
      "nurse",
      "caregiver",
      "social worker",
    ],
    context_aliases: [
      "patient",
      "soins",
      "clinique",
      "hopital",
      "prise en charge",
      "accompagnement social",
    ],
    skill_aliases: [
      "nursing",
      "soins infirmiers",
      "sante communautaire",
      "care",
    ],
    company_hints: ["clinic", "hospital", "medical", "social"],
    source_hints: ["health", "medical"],
    legacy_hints: ["health"],
    adjacent_families: [
      "cleaning_hygiene",
      "public_ngo_development",
      "education_research",
    ],
    status: "active",
  }),
  retail_sales_checkout: defineFamily({
    key: "retail_sales_checkout",
    label: "Retail / vente / commerce / caisse",
    short_label: "Retail / commerce",
    aliases_fr: [
      "retail",
      "vente",
      "commerce",
      "caisse",
      "boutique",
      "magasin",
    ],
    aliases_en: [
      "retail",
      "store",
      "shop",
      "checkout",
      "cashier",
      "merchandising",
    ],
    strong_title_aliases: [
      "caissier",
      "vendeur boutique",
      "conseiller de vente",
      "directeur de magasin",
      "directeur supermarche",
      "directeur retail",
      "cashier",
      "sales assistant",
      "store manager",
      "merchandiser",
    ],
    context_aliases: [
      "encaissement",
      "mise en rayon",
      "vente magasin",
      "point de vente",
      "boutique",
    ],
    skill_aliases: [
      "caisse",
      "merchandising",
      "service client",
      "vente detail",
    ],
    company_hints: ["retail", "shop", "store", "boutique"],
    source_hints: ["retail", "commerce"],
    legacy_hints: [],
    adjacent_families: [
      "commercial_business_customer",
      "hospitality_food_tourism",
      "logistics_supply_warehouse",
    ],
    status: "active",
  }),
  agriculture_agro: defineFamily({
    key: "agriculture_agro",
    label: "Agriculture / élevage / agro",
    short_label: "Agriculture / agro",
    aliases_fr: [
      "agriculture",
      "elevage",
      "agro",
      "agroalimentaire",
      "agronomie",
    ],
    aliases_en: ["agriculture", "farming", "livestock", "agro", "agronomy"],
    strong_title_aliases: [
      "agronome",
      "technicien agricole",
      "responsable exploitation agricole",
      "farm manager",
      "agriculture officer",
    ],
    context_aliases: [
      "culture",
      "recolte",
      "elevage",
      "ferme",
      "production agricole",
    ],
    skill_aliases: ["agronomie", "irrigation", "elevage", "agroalimentaire"],
    company_hints: ["agro", "farm", "agriculture"],
    source_hints: ["agro", "agriculture"],
    legacy_hints: [],
    adjacent_families: [
      "industry_production",
      "logistics_supply_warehouse",
      "public_ngo_development",
    ],
    status: "active",
  }),
  admin_support: defineFamily({
    key: "admin_support",
    label: "Administratif / secrétariat / support",
    short_label: "Administratif / support",
    aliases_fr: [
      "administratif",
      "secretariat",
      "support",
      "back office",
      "assistant",
    ],
    aliases_en: [
      "administration",
      "administrative",
      "office support",
      "back office",
      "secretarial",
    ],
    strong_title_aliases: [
      "assistant administratif",
      "secretaire",
      "office assistant",
      "administrative assistant",
      "back office officer",
      "receptionniste",
    ],
    context_aliases: [
      "classement",
      "courrier",
      "accueil",
      "saisie",
      "support administratif",
    ],
    skill_aliases: [
      "microsoft office",
      "secretariat",
      "gestion documentaire",
      "data entry",
    ],
    company_hints: ["office", "administration", "support"],
    source_hints: ["administration", "support"],
    legacy_hints: ["hr_admin"],
    adjacent_families: [
      "hr_recruitment_training",
      "finance_accounting_audit",
      "retail_sales_checkout",
    ],
    status: "active",
  }),
  finance_accounting_audit: defineFamily({
    key: "finance_accounting_audit",
    label: "Finance / comptabilité / audit",
    short_label: "Finance / comptabilité",
    aliases_fr: [
      "finance",
      "comptabilite",
      "audit",
      "controle de gestion",
      "tresorerie",
    ],
    aliases_en: ["finance", "accounting", "audit", "controlling", "treasury"],
    strong_title_aliases: [
      "comptable",
      "chef comptable",
      "directeur comptable",
      "directeur financier",
      "controleur de gestion",
      "auditeur",
      "financial controller",
      "accountant",
      "finance manager",
    ],
    context_aliases: [
      "bilan",
      "budget",
      "lettrage",
      "tresorerie",
      "etats financiers",
    ],
    skill_aliases: [
      "sap fi",
      "quickbooks",
      "excel",
      "ifrs",
      "comptabilite generale",
    ],
    company_hints: ["finance", "audit", "accounting"],
    source_hints: ["finance", "audit"],
    legacy_hints: ["finance", "finance_accounting"],
    adjacent_families: [
      "admin_support",
      "legal_compliance",
      "management_project",
    ],
    status: "active",
  }),
  hr_recruitment_training: defineFamily({
    key: "hr_recruitment_training",
    label: "RH / recrutement / formation",
    short_label: "RH / recrutement",
    aliases_fr: [
      "rh",
      "ressources humaines",
      "recrutement",
      "formation",
      "talent",
    ],
    aliases_en: [
      "human resources",
      "hr",
      "recruitment",
      "talent acquisition",
      "learning",
    ],
    strong_title_aliases: [
      "charge de recrutement",
      "responsable rh",
      "gestionnaire rh",
      "recruiter",
      "hr officer",
      "training coordinator",
    ],
    context_aliases: [
      "talent acquisition",
      "formation",
      "gestion du personnel",
      "paie",
      "onboarding",
    ],
    skill_aliases: ["ats", "recrutement", "formation", "payroll", "hris"],
    company_hints: ["talent", "hr", "recruitment"],
    source_hints: ["hr", "recruitment"],
    legacy_hints: ["hr", "hr_admin"],
    adjacent_families: [
      "admin_support",
      "management_project",
      "public_ngo_development",
    ],
    status: "active",
  }),
  marketing_communication_content: defineFamily({
    key: "marketing_communication_content",
    label: "Marketing / communication / contenu",
    short_label: "Marketing / communication",
    aliases_fr: [
      "marketing",
      "communication",
      "contenu",
      "media",
      "marque",
      "digital",
    ],
    aliases_en: [
      "marketing",
      "communication",
      "content",
      "media",
      "brand",
      "digital marketing",
    ],
    strong_title_aliases: [
      "community manager",
      "charge de communication",
      "content manager",
      "social media manager",
      "copywriter",
      "brand manager",
    ],
    context_aliases: [
      "seo",
      "sea",
      "reseaux sociaux",
      "campagne",
      "content",
      "branding",
    ],
    skill_aliases: [
      "google ads",
      "meta ads",
      "seo",
      "copywriting",
      "content creation",
    ],
    company_hints: ["marketing", "media", "communication"],
    source_hints: ["marketing", "communication"],
    legacy_hints: ["marketing", "marketing_comms"],
    adjacent_families: [
      "commercial_business_customer",
      "retail_sales_checkout",
      "tech_data_product_design",
    ],
    status: "active",
  }),
  commercial_business_customer: defineFamily({
    key: "commercial_business_customer",
    label: "Commercial / business development / relation client",
    short_label: "Commercial / business",
    aliases_fr: [
      "commercial",
      "business development",
      "relation client",
      "vente b2b",
      "partenariat",
      "developpement commercial",
    ],
    aliases_en: [
      "sales",
      "business development",
      "account management",
      "customer relations",
      "partnerships",
    ],
    strong_title_aliases: [
      "business developer",
      "business development",
      "sales developer",
      "developpement commercial",
      "commercial terrain",
      "directeur commercial",
      "account manager",
      "account executive",
      "customer success manager",
      "sales representative",
      "relation client",
    ],
    context_aliases: [
      "prospection",
      "crm",
      "pipeline commercial",
      "portefeuille client",
      "closing",
    ],
    skill_aliases: [
      "salesforce",
      "crm",
      "negociation",
      "account management",
      "customer success",
    ],
    company_hints: ["sales", "business", "customer", "crm"],
    source_hints: ["sales", "bizdev"],
    legacy_hints: ["sales", "customer", "sales_bizdev", "customer_success"],
    adjacent_families: [
      "retail_sales_checkout",
      "marketing_communication_content",
      "management_project",
    ],
    status: "active",
  }),
  tech_data_product_design: defineFamily({
    key: "tech_data_product_design",
    label: "Tech / data / produit / design",
    short_label: "Tech / data / produit",
    aliases_fr: [
      "tech",
      "data",
      "design",
      "informatique",
      "developpement",
    ],
    aliases_en: [
      "tech",
      "data",
      "design",
      "software",
      "engineering",
    ],
    strong_title_aliases: [
      "developpeur",
      "software developer",
      "python developer",
      "java developer",
      "java engineer",
      "react developer",
      "frontend developer",
      "backend developer",
      "fullstack developer",
      "mobile developer",
      "qa engineer",
      "test automation engineer",
      "qa test automation engineer",
      "software engineer",
      "security architect",
      "security analyst",
      "application security",
      "cloud security",
      "devsecops",
      "soc analyst",
      "data analyst",
      "data engineer",
      "technical product manager",
      "product engineer",
      "product platform",
      "product engineering",
      "ux designer",
      "ui designer",
      "devops engineer",
    ],
    context_aliases: [
      "frontend",
      "backend",
      "full stack",
      "analytics",
      "bi",
      "qa",
      "soc",
      "iam",
      "product platform",
      "product engineering",
      "cybersecurity",
    ],
    skill_aliases: [
      "sql",
      "python",
      "typescript",
      "react",
      "node.js",
      "figma",
      "power bi",
      "tableau",
      "aws",
      "docker",
    ],
    company_hints: ["tech", "software", "digital"],
    source_hints: ["tech", "data"],
    legacy_hints: [
      "data",
      "engineering",
      "devops",
      "tech",
      "data_ai",
      "engineering",
    ],
    adjacent_families: [
      "marketing_communication_content",
      "finance_accounting_audit",
      "management_project",
      "commercial_business_customer",
    ],
    status: "active",
  }),
  legal_compliance: defineFamily({
    key: "legal_compliance",
    label: "Juridique / conformité",
    short_label: "Juridique / conformité",
    aliases_fr: [
      "juridique",
      "conformite",
      "droit",
      "reglementaire",
    ],
    aliases_en: ["legal", "regulatory", "governance", "privacy"],
    strong_title_aliases: [
      "juriste",
      "legal counsel",
      "compliance officer",
      "compliance manager",
      "responsable juridique",
      "contract manager",
      "privacy officer",
    ],
    context_aliases: [
      "conformite",
      "regulatory compliance",
      "rgpd",
      "gouvernance",
      "due diligence",
      "legal advisory",
      "privacy law",
    ],
    skill_aliases: [
      "contract drafting",
      "contract negotiation",
      "gdpr",
      "legal research",
    ],
    company_hints: ["legal", "compliance", "juridique"],
    source_hints: ["legal", "compliance"],
    legacy_hints: ["legal", "legal_compliance"],
    adjacent_families: [
      "finance_accounting_audit",
      "public_ngo_development",
      "management_project",
    ],
    status: "active",
  }),
  education_research: defineFamily({
    key: "education_research",
    label: "Éducation / enseignement / recherche",
    short_label: "Éducation / recherche",
    aliases_fr: [
      "education",
      "enseignement",
      "recherche",
      "pedagogie",
      "academique",
    ],
    aliases_en: ["education", "teaching", "research", "academic", "training"],
    strong_title_aliases: [
      "enseignant",
      "professeur",
      "formateur",
      "teacher",
      "lecturer",
      "research officer",
      "research assistant",
    ],
    context_aliases: [
      "cours",
      "pedagogie",
      "curriculum",
      "laboratoire",
      "recherche",
    ],
    skill_aliases: [
      "teaching",
      "research methods",
      "pedagogie",
      "publication scientifique",
    ],
    company_hints: ["school", "university", "education", "research"],
    source_hints: ["education", "research"],
    legacy_hints: [],
    adjacent_families: [
      "healthcare_social_care",
      "public_ngo_development",
      "hr_recruitment_training",
    ],
    status: "active",
  }),
  public_ngo_development: defineFamily({
    key: "public_ngo_development",
    label: "Public / ONG / institutionnel / développement",
    short_label: "Public / ONG / développement",
    aliases_fr: [
      "public",
      "ong",
      "institutionnel",
      "humanitaire",
      "cooperation",
    ],
    aliases_en: [
      "public sector",
      "ngo",
      "institutional",
      "humanitarian",
      "donor",
    ],
    strong_title_aliases: [
      "programme officer",
      "project officer",
      "development officer",
      "humanitarian coordinator",
      "monitoring and evaluation officer",
      "grant officer",
    ],
    context_aliases: [
      "bailleur",
      "collectivite",
      "developpement international",
      "projet de developpement",
      "humanitaire",
      "monitoring and evaluation",
    ],
    skill_aliases: [
      "m&e",
      "grant management",
      "proposal writing",
      "monitoring and evaluation",
      "donor reporting",
    ],
    company_hints: [
      "ngo",
      "foundation",
      "ministry",
      "united nations",
      "development",
    ],
    source_hints: ["ngo", "development", "institution"],
    legacy_hints: ["ngo_development"],
    adjacent_families: [
      "management_project",
      "healthcare_social_care",
      "education_research",
      "legal_compliance",
    ],
    status: "active",
  }),
  management_project: defineFamily({
    key: "management_project",
    label: "Direction / management / gestion de projet",
    short_label: "Management / projet",
    aliases_fr: [
      "direction",
      "management",
      "gestion de projet",
      "pilotage",
      "coordination",
    ],
    aliases_en: [
      "management",
      "leadership",
      "project management",
      "program management",
      "coordination",
    ],
    strong_title_aliases: [
      "chef de projet",
      "project manager",
      "program manager",
      "operations manager",
      "country manager",
      "head of",
    ],
    context_aliases: [
      "coordination",
      "pilotage",
      "gouvernance projet",
      "pmo",
      "programme management",
    ],
    skill_aliases: [
      "project management",
      "pmo",
      "stakeholder management",
      "budget management",
    ],
    company_hints: ["management", "project"],
    source_hints: ["management", "project"],
    legacy_hints: ["pm", "project_programme"],
    adjacent_families: [
      "construction_trades",
      "logistics_supply_warehouse",
      "finance_accounting_audit",
      "hr_recruitment_training",
      "commercial_business_customer",
      "public_ngo_development",
      "tech_data_product_design",
    ],
    status: "active",
  }),
  other_uncategorized: defineFamily({
    key: "other_uncategorized",
    label: "Autres / non classés",
    short_label: "Autres / non classés",
    aliases_fr: ["autres", "non classes", "non classe", "autre"],
    aliases_en: ["other", "uncategorized", "general"],
    strong_title_aliases: [],
    context_aliases: [],
    skill_aliases: [],
    company_hints: [],
    source_hints: [],
    legacy_hints: ["general", "uncategorized"],
    adjacent_families: [],
    status: "active",
  }),
};

export function normalizeTaxonomyText(
  value: string | null | undefined,
): string {
  return (value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9+/&.\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function getJobFamilyDefinition(key: JobFamilyKey): JobFamilyDefinition {
  return JOB_FAMILY_TAXONOMY[key];
}

export function getAllTaxonomyLookupTerms(
  definition: JobFamilyDefinition,
): string[] {
  return [
    definition.label,
    definition.short_label,
    ...definition.aliases_fr,
    ...definition.aliases_en,
    ...definition.strong_title_aliases,
    ...definition.context_aliases,
    ...definition.skill_aliases,
    ...definition.company_hints,
    ...definition.source_hints,
    ...definition.legacy_hints,
  ]
    .map((item) => normalizeTaxonomyText(item))
    .filter(Boolean);
}

export function findJobFamilyByAlias(
  value: string | null | undefined,
): JobFamilyKey | null {
  const normalized = normalizeTaxonomyText(value);
  if (!normalized) return null;

  for (const key of JOB_FAMILY_ORDER) {
    const definition = JOB_FAMILY_TAXONOMY[key];
    if (getAllTaxonomyLookupTerms(definition).includes(normalized)) return key;
  }

  return null;
}
